server:
  port: 8090

spring:
  application:
    name: api-geteway
#  security:
#    user:
#      password: user  # 直接登录时的密码
#    ignored: /
#    sessions: never   # session策略
#    oauth2:
#      sso:
#        loginPath: /login   # 登录路径
#      client:
#        clientId: 你的clientId
#        clientSecret: 你的clientSecret
#        accessTokenUri: https://github.com/login/oauth/access_token
#        userAuthorizationUri: https://github.com/login/oauth/authorize
#      resource:
#        userInfoUri: https://api.github.com/user
#        preferTokenInfo: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/