server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.100:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka

