server:
  port: 8091

spring:
  application:
    name: mall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liaofuxing
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

