server:
  port: 8092

spring:
  application:
    name: mall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.100:3306/springcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.100:8761/eureka/

feign:
  hystrix:
    enabled: true
